import type { DuplicateGroup } from '../types';

export interface GeneratedPatch {
  moduleFiles: { path: string; content: string }[];
  applyScript: string;
  manifestJson: string;
  reportMarkdown: string;
}

interface ManifestEntry {
  groupId: string;
  modulePath: string;
  functionName: string;
  originalText: string;
  isJsx: boolean;
  occurrences: { filePath: string; startLine: number; endLine: number }[];
}

export function buildPatch(duplicateGroups: DuplicateGroup[], selectedIds: string[]): GeneratedPatch {
  const selected = duplicateGroups.filter((g) => selectedIds.includes(g.id));

  const moduleFiles: { path: string; content: string }[] = [];
  const manifestEntries: ManifestEntry[] = [];
  let reportMarkdown = `# Refactor Report\n\nGenerated by App #41 — Repo Duplicate & Capability Analyzer.\n\n`;

  selected.forEach((group, idx) => {
    const fnName = suggestFunctionName(group, idx);
    const isJsx = /^\s*</.test(group.representativeCode.trim());
    const modulePath = isJsx ? group.suggestedModuleName.replace(/\.ts$/, '.tsx') : group.suggestedModuleName;

    const bodyLines = isJsx
      ? [`return (`, indent(group.representativeCode), `);`]
      : [indent(group.representativeCode)];

    const moduleContent =
      `// Auto-extracted by App #41 from ${group.occurrences.length} duplicate location(s).\n` +
      `// Review before use — parameters may need adjusting, especially if this was a "near" match.\n\n` +
      (isJsx ? `import React from 'react';\n\n` : '') +
      `export function ${fnName}()${isJsx ? ': React.ReactElement' : ''} {\n${bodyLines.join('\n')}\n}\n`;

    moduleFiles.push({ path: modulePath, content: moduleContent });

    reportMarkdown += `## ${modulePath}\n\n`;
    reportMarkdown += `- Kind: ${
      group.kind === 'exact' ? 'Exact duplicate — safe to auto-replace' : 'Near duplicate — manual review needed, NOT auto-replaced'
    }\n`;
    reportMarkdown += `- Confidence: ${group.confidence}%\n`;
    reportMarkdown += `- Found ${group.occurrences.length} times:\n`;
    group.occurrences.forEach((occ) => {
      reportMarkdown += `  - ${occ.filePath}:${occ.startLine}-${occ.endLine}\n`;
    });
    reportMarkdown += `\n`;

    if (group.kind === 'exact') {
      manifestEntries.push({
        groupId: group.id,
        modulePath,
        functionName: fnName,
        originalText: group.representativeCode,
        isJsx,
        occurrences: group.occurrences.map((o) => ({ filePath: o.filePath, startLine: o.startLine, endLine: o.endLine }))
      });
    }
  });

  reportMarkdown += `## How to apply\n\n`;
  reportMarkdown += `1. Unzip this patch into your repo root.\n`;
  reportMarkdown += `2. Run \`node apply-refactor.mjs --dry-run\` to preview changes (nothing is written).\n`;
  reportMarkdown += `3. If it looks right, run \`node apply-refactor.mjs --apply\` (this makes \`.bak\` backups of every file it touches before writing).\n`;
  reportMarkdown += `4. Run your normal build (\`npm run build:termux\`) to confirm nothing broke.\n`;
  reportMarkdown += `5. "Near duplicate" groups above were NOT auto-replaced — review those manually and extract them by hand if you agree with the suggestion.\n`;

  return {
    moduleFiles,
    applyScript: buildApplyScriptSource(),
    manifestJson: JSON.stringify({ entries: manifestEntries }, null, 2),
    reportMarkdown
  };
}

function suggestFunctionName(group: DuplicateGroup, idx: number): string {
  const match =
    group.representativeCode.match(/function\s+([A-Za-z_$][A-Za-z0-9_$]*)/) ||
    group.representativeCode.match(/const\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=/);
  return match ? match[1] : `sharedHelper${idx + 1}`;
}

function indent(code: string): string {
  return code
    .split('\n')
    .map((l) => (l.trim() ? `  ${l}` : l))
    .join('\n');
}

function buildApplyScriptSource(): string {
  const lines = [
    '#!/usr/bin/env node',
    '/**',
    ' * Auto-generated by App #41 — Repo Duplicate & Capability Analyzer.',
    ' *',
    ' * Usage:',
    ' *   node apply-refactor.mjs --dry-run   (preview only, changes nothing — this is the default)',
    ' *   node apply-refactor.mjs --apply     (writes changes, makes .bak backups first)',
    ' *',
    ' * Only "exact" duplicate groups are auto-replaced. Run this from your repo root.',
    ' */',
    "import fs from 'fs';",
    "import path from 'path';",
    '',
    'const args = process.argv.slice(2);',
    "const isApply = args.includes('--apply');",
    'const isDryRun = !isApply;',
    '',
    "const manifest = JSON.parse(fs.readFileSync(new URL('./refactor-manifest.json', import.meta.url)));",
    '',
    'let changed = 0;',
    'let skipped = 0;',
    '',
    'for (const entry of manifest.entries) {',
    '  for (const occ of entry.occurrences) {',
    '    const filePath = path.resolve(process.cwd(), occ.filePath);',
    '    if (!fs.existsSync(filePath)) {',
    "      console.log('SKIP (file not found): ' + occ.filePath);",
    '      skipped++;',
    '      continue;',
    '    }',
    '',
    "    const content = fs.readFileSync(filePath, 'utf8');",
    '    if (!content.includes(entry.originalText.trim())) {',
    "      console.log('SKIP (text moved/changed since scan): ' + occ.filePath);",
    '      skipped++;',
    '      continue;',
    '    }',
    '',
    '    const importPath = toImportPath(occ.filePath, entry.modulePath);',
    "    const importLine = \"import { \" + entry.functionName + \" } from '\" + importPath + \"';\\n\";",
    "    const replacement = entry.isJsx ? '{' + entry.functionName + '()}' : entry.functionName + '()';",
    '',
    "    console.log((isDryRun ? '[DRY RUN] Would replace' : 'Replacing') + ' in ' + occ.filePath + ' (lines ' + occ.startLine + '-' + occ.endLine + ')');",
    '',
    '    if (isApply) {',
    "      fs.writeFileSync(filePath + '.bak', content);",
    '      let updated = content.replace(entry.originalText.trim(), replacement);',
    '      if (!updated.includes(importLine.trim())) {',
    '        updated = importLine + updated;',
    '      }',
    '      fs.writeFileSync(filePath, updated);',
    '    }',
    '    changed++;',
    '  }',
    '}',
    '',
    'function toImportPath(fromFile, toModule) {',
    '  const fromDir = path.dirname(fromFile);',
    "  let rel = path.relative(fromDir, toModule).replace(/\\\\/g, '/').replace(/\\.ts$/, '');",
    "  if (!rel.startsWith('.')) rel = './' + rel;",
    '  return rel;',
    '}',
    '',
    "console.log('');",
    "console.log((isDryRun ? 'DRY RUN complete: ' : 'APPLY complete: ') + changed + ' replacement(s), ' + skipped + ' skipped.');",
    'if (isDryRun) {',
    "  console.log('Run again with --apply to actually write changes (backups will be made as .bak files).');",
    '}',
    ''
  ];
  return lines.join('\n');
}
