import type { RepoFile, FunctionInventoryEntry, ComplexityEntry } from '../types';

export function buildFunctionInventory(files: RepoFile[]): FunctionInventoryEntry[] {
  const entries: FunctionInventoryEntry[] = [];
  const fnRegex = /export\s+(?:default\s+)?function\s+([A-Za-z_$][A-Za-z0-9_$]*)/g;
  const constRegex = /export\s+const\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*[:=]/g;

  files.forEach((f) => {
    if (!(f.path.endsWith('.ts') || f.path.endsWith('.tsx'))) return;

    let m: RegExpExecArray | null;
    fnRegex.lastIndex = 0;
    while ((m = fnRegex.exec(f.content))) {
      entries.push({ name: m[1], filePath: f.path, kind: 'function' });
    }
    constRegex.lastIndex = 0;
    while ((m = constRegex.exec(f.content))) {
      entries.push({ name: m[1], filePath: f.path, kind: 'const' });
    }
  });

  return entries;
}

export function buildDependencyGraph(files: RepoFile[]): string[] {
  const lines: string[] = [];
  const importRegex = /import\s+(?:[\w*{}\s,]+\s+from\s+)?["']([^"']+)["']/g;

  files.forEach((f) => {
    if (!(f.path.endsWith('.ts') || f.path.endsWith('.tsx'))) return;

    const targets = new Set<string>();
    let m: RegExpExecArray | null;
    importRegex.lastIndex = 0;
    while ((m = importRegex.exec(f.content))) {
      const target = m[1];
      if (
        target.startsWith('@apps/') ||
        target.startsWith('@core/') ||
        target.startsWith('@shared/') ||
        target.startsWith('./') ||
        target.startsWith('../')
      ) {
        targets.add(target);
      }
    }

    if (targets.size > 0) {
      lines.push(f.path);
      targets.forEach((t) => lines.push(`  \u2192 ${t}`));
    }
  });

  return lines;
}

export function rankComplexity(files: RepoFile[]): ComplexityEntry[] {
  const CONTROL_FLOW = /\b(if|for|while|switch|catch)\b|&&|\|\||\?/g;

  const ranked: ComplexityEntry[] = files
    .filter((f) => f.path.endsWith('.ts') || f.path.endsWith('.tsx'))
    .map((f) => {
      const lines = f.content.split('\n').length;
      const matches = f.content.match(CONTROL_FLOW);
      const complexityScore = (matches ? matches.length : 0) + Math.round(lines / 20);
      return { filePath: f.path, lines, complexityScore };
    });

  ranked.sort((a, b) => b.complexityScore - a.complexityScore);
  return ranked.slice(0, 20);
}

export function generateRepoMap(
  files: RepoFile[],
  isHubApps: boolean,
  functionInventory: FunctionInventoryEntry[],
  complexity: ComplexityEntry[]
): string {
  const appFolders = new Set<string>();
  files.forEach((f) => {
    const m = f.path.match(/^src\/apps\/([^/]+)\//);
    if (m) appFolders.add(m[1]);
  });

  const totalLines = files.reduce((sum, f) => sum + f.content.split('\n').length, 0);

  let md = `# Repository Map\n\n`;
  md += `Generated by App #41 — Repo Duplicate & Capability Analyzer.\n\n`;
  md += `- Total analyzed files: ${files.length}\n`;
  md += `- Total lines of code (approx): ${totalLines}\n`;
  md += `- Detected structure: ${
    isHubApps ? '1Hub Apps monorepo (src/apps/<slug>/ convention detected)' : 'Generic JS/TS repository'
  }\n\n`;

  if (isHubApps && appFolders.size > 0) {
    md += `## Apps (${appFolders.size})\n\n`;
    Array.from(appFolders)
      .sort()
      .forEach((slug) => {
        const manifestFile = files.find((f) => f.path === `src/apps/${slug}/manifest.json`);
        if (manifestFile) {
          try {
            const manifest = JSON.parse(manifestFile.content);
            md += `- **${slug}** — ${manifest.description || '(no description)'}\n`;
          } catch {
            md += `- **${slug}**\n`;
          }
        } else {
          md += `- **${slug}**\n`;
        }
      });
    md += `\n`;
  }

  md += `## Largest / Most Complex Files\n\n`;
  complexity.slice(0, 10).forEach((c) => {
    md += `- ${c.filePath} (${c.lines} lines, complexity score ${c.complexityScore})\n`;
  });
  md += `\n`;

  md += `## Exported Functions/Components (${functionInventory.length} total)\n\n`;
  md += `Full inventory is included in the in-app report — this file only summarizes the count above.\n`;

  return md;
}
