export interface AppDefinition {
  id: string
  number: string
  name: string
  description: string
  path: string
  tags: string[]
}

export const APP_REGISTRY: AppDefinition[] = [
  {
    id: 'smart-image-tools',
    number: '001',
    name: 'Smart Image Tools',
    description: 'Compress, resize, convert and crop images directly in your browser.',
    path: '/apps/smart-image-tools',
    tags: ['Compress', 'Resize', 'Convert', 'Crop'],
  },
  {
    id: 'smart-pdf-tools',
    number: '002',
    name: 'Smart PDF Tools',
    description: 'Create, merge, split, reorder, rotate and compress PDFs directly in your browser.',
    path: '/apps/smart-pdf-tools',
    tags: ['Merge', 'Split', 'Compress', 'Images to PDF'],
  },
  {
    id: 'qr-barcode-studio',
    number: '003',
    name: 'QR & Barcode Studio',
    description: 'Create and scan QR codes and barcodes privately in your browser.',
    path: '/apps/qr-barcode-studio',
    tags: ['QR Generator', 'Barcode', 'Scanner', 'Wi-Fi QR'],
  },
  {
    id: 'smart-text-tools',
    number: '004',
    name: 'Smart Text Tools',
    description: 'Clean, convert, compare and extract useful data from text instantly.',
    path: '/apps/smart-text-tools',
    tags: ['Text Cleaner', 'Case Converter', 'Compare', 'JSON'],
  },
  {
    id: 'smart-data-tools',
    number: '005',
    name: "Smart Data Tools",
    description: "Clean, convert, filter and export CSV and JSON data directly in your browser.",
    path: '/apps/smart-data-tools',
    tags: ["CSV","JSON","Data Cleaner","Converter"],
  },
  {
    id: 'smart-calculator-converter',
    number: '006',
    name: "Smart Calculator & Converter",
    description: "Calculate EMI, estimate existing loans, GST, discounts, dates and everyday unit conversions.",
    path: '/apps/smart-calculator-converter',
    tags: ["EMI","GST","Converter","Calculator"],
  },
  {
    id: 'smart-file-tools',
    number: '007',
    name: "Smart File Tools",
    description: "Rename, inspect, hash, deduplicate, archive, split and merge files locally in your browser.",
    path: '/apps/smart-file-tools',
    tags: ["Bulk Rename","SHA-256","Duplicate Detection","ZIP Tools","File Split","Merge Chunks"],
  },
  {
    id: 'smart-document-scanner-ocr',
    number: '008',
    name: "Smart Document Scanner & OCR",
    description: "Scan, enhance and extract text from documents locally in your browser.",
    path: '/apps/smart-document-scanner-ocr',
    tags: ["Document Scanner","OCR","Perspective Correction","Deskew","Scan Enhancement","PDF Export"],
  },
  {
    id: 'smart-audio-tools',
    number: '009',
    name: "Smart Audio Tools",
    description: "Trim, merge, adjust and export audio locally in your browser.",
    path: '/apps/smart-audio-tools',
    tags: ["Audio Trim","Merge Audio","Volume","Fade","Speed","WAV Export"],
  },
  {
    id: 'smart-video-tools',
    number: '010',
    name: "Smart Video Tools",
    description: "Trim, resize, rotate, mute, extract audio and convert videos locally in your browser.",
    path: '/apps/smart-video-tools',
    tags: ["Video Trim","Resize","Compress","Rotate","Mute","Extract Audio"],
  },
  {
    id: 'smart-password-generator',
    number: '011',
    name: "Smart Password Generator",
    description: "Generate strong, random passwords locally in your browser.",
    path: '/apps/smart-password-generator',
    tags: ["Password Generator","Strong Password","Random Password","Security"],
  },
  {
    id: 'smart-uuid-generator',
    number: '012',
    name: "Smart UUID Generator",
    description: "Generate secure UUID v4 identifiers locally in your browser.",
    path: '/apps/smart-uuid-generator',
    tags: ["UUID Generator","UUID v4","Bulk UUID","Developer Tools"],
  },
  {
    id: 'smart-metadata-privacy-tools',
    number: '013',
    name: "Smart Metadata & Privacy Tools",
    description: "Inspect and remove privacy-sensitive metadata from files directly in your browser.",
    path: '/apps/smart-metadata-privacy-tools',
    tags: ["Metadata","EXIF","Privacy Cleaner","Image Metadata","File Inspector"],
  },
  {
    id: 'smart-archive-tools',
    number: '014',
    name: "Smart Archive Tools",
    description: "Create, inspect, and extract ZIP archives privately in your browser.",
    path: '/apps/smart-archive-tools',
    tags: ["ZIP Creator","ZIP Extractor","Archive Browser","File Compression"],
  },
  {
    id: 'smart-network-web-tools',
    number: '015',
    name: "Smart Network & Web Tools",
    description: "Analyze URLs, encode data, calculate IPv4/CIDR ranges and inspect browser details locally.",
    path: '/apps/smart-network-web-tools',
    tags: ["Network Tools","URL Tools","Developer Tools","IPv4","CIDR","Base64"],
  },
  {
    id: 'smart-screenshot-tools',
    number: '016',
    name: "Smart Screenshot Tools",
    description: "Stitch, blur, annotate and export screenshots locally in your browser.",
    path: '/apps/smart-screenshot-tools',
    tags: ["Screenshot Stitcher","Blur Sensitive Areas","Annotations","Long Screenshot","Image Export"],
  },
  {
    id: 'smart-color-design-tools',
    number: '028',
    name: "Smart Color & Design Tools",
    description: "Pick colors, extract palettes, generate gradients and check accessibility locally in your browser.",
    path: '/apps/smart-color-design-tools',
    tags: ["Color Picker","Palette Extractor","Gradient Generator","Contrast Checker","WCAG","Color Converter"],
  },
  {
    id: 'universal-test-asset-factory',
    number: '017',
    name: "Universal Test Asset Factory",
    description: "Generate rich reusable test files locally for OCR, documents, spreadsheets, QR/barcodes, cross-app workflows and automated demos.",
    path: '/apps/universal-test-asset-factory',
    tags: ["Test Assets","OCR","PDF","Spreadsheet","QR","Barcode"],
  },
  {
    id: 'local-screen-tab-recorder',
    number: '018',
    name: "Local Screen & Tab Recorder",
    description: "Record a user-selected browser tab, window or screen locally with explicit browser permission, reusable recording controls and WebM export.",
    path: '/apps/local-screen-tab-recorder',
    tags: ["Screen Recorder","Tab Recorder","Window Capture","WebM","Local Recording"],
  },
  {
    id: 'browser-video-processing-studio',
    number: '019',
    name: "Browser Video Processing Studio",
    description: "Edit, process and polish videos locally in your browser with reusable demo-video processing tools.",
    path: '/apps/browser-video-processing-studio',
    tags: ["Video Editing","Trim Video","Resize Video","Aspect Ratio","Demo Video Processing"],
  },
  {
    id: 'web-interaction-simulation-engine',
    number: '020',
    name: "Web Interaction Simulation Engine",
    description: "Create, validate and visually simulate reusable structured demo actions locally in your browser.",
    path: '/apps/web-interaction-simulation-engine',
    tags: ["Interaction Simulation","Demo Actions","Cursor Animation","Typing Simulation","Workflow Automation"],
  },
  {
    id: 'website-structure-feature-analyzer',
    number: '021',
    name: "Website Structure & Feature Analyzer",
    description: "Analyze accessible website and page data into reusable structured Page Maps and Feature Maps using browser-local rules.",
    path: '/apps/website-structure-feature-analyzer',
    tags: ["Website Analyzer","Page Map","Feature Map","HTML Analyzer","Workflow Detection"],
  },
  {
    id: 'web-page-snapshot-local-simulation',
    number: '022',
    name: "Web Page Snapshot & Local Simulation",
    description: "Create temporary browser-local page snapshots and simulation targets from accessible HTML, user-provided source or structured Page Maps.",
    path: '/apps/web-page-snapshot-local-simulation',
    tags: ["Web Snapshot","Local Simulation","HTML Preview","Page Map","IndexedDB"],
  },
  {
    id: 'rule-based-demo-flow-builder',
    number: '023',
    name: "Rule-Based Demo Flow Builder",
    description: "Generate deterministic editable demo workflows from structured Page Maps and convert them into reusable interaction sequences without AI.",
    path: '/apps/rule-based-demo-flow-builder',
    tags: ["Demo Flow","Workflow Builder","Rule-Based Automation","Interaction Sequence","Page Map"],
  },
  {
    id: 'smart-asset-to-action-mapper',
    number: '024',
    name: "Smart Asset-to-Action Mapper",
    description: "Map demo file-input requirements to reusable App #017 test-asset generation requests and App #020 upload actions.",
    path: '/apps/smart-asset-to-action-mapper',
    tags: ["Asset Mapping","Demo Assets","Upload Actions","Test Asset Factory","Workflow Automation"],
  },
  {
    id: 'visual-capture-demo-fallback-engine',
    number: '025',
    name: "Visual Capture & Demo Fallback Engine",
    description: "Create truthful user-permitted visual demo captures with reusable cursor, click, focus, zoom and caption cues when direct page automation is unavailable.",
    path: '/apps/visual-capture-demo-fallback-engine',
    tags: ["Visual Capture","Demo Fallback","Screen Capture","Cursor Effects","Demo Recording"],
  },
  {
    id: 'automated-demo-workflow-orchestrator',
    number: '026',
    name: "Automated Demo Workflow Orchestrator",
    description: "Coordinate reusable analysis, snapshot, flow, asset, simulation, capture and video-processing capabilities into one browser-first demo workflow.",
    path: '/apps/automated-demo-workflow-orchestrator',
    tags: ["Workflow Orchestrator","Automated Demo","Demo Pipeline","Workflow Automation","Stage Tracking"],
  },
  {
    id: 'automatic-website-demo-video-generator',
    number: '027',
    name: "Automatic Website Demo Video Generator",
    description: "Generate website and app demo videos through the reusable 1 Hub Apps automated demo workflow pipeline.",
    path: '/apps/automatic-website-demo-video-generator',
    tags: ["Website Demo Video","Automatic Demo","Demo Generator","Workflow Orchestration","Video Automation"],
  },
  {
    id: 'smart-image-background-tools',
    number: '029',
    name: "Smart Image Background Tools",
    description: "Remove flat or mostly uniform image backgrounds locally with color controls, manual brush refinement and flexible exports.",
    path: '/apps/smart-image-background-tools',
    tags: ["Background Removal","Color Key","Manual Erase","Transparent PNG","Blur Background","Image Export"],
  },
  {
    id: 'smart-document-scan-auto-crop-engine',
    number: '030',
    name: "Smart Document Scan & Auto-Crop Engine",
    description: "Detect document edges, correct perspective, enhance scans and export clean document images locally in your browser.",
    path: '/apps/smart-document-scan-auto-crop-engine',
    tags: ["Document Scanner","Auto Crop","Perspective Correction","Camera Scan","Scan Enhancement"],
  },
  {
    id: 'smart-document-classifier',
    number: '031',
    name: "Smart Document Classifier",
    description: "Classify PDFs, DOCX files, text documents and scanned images locally using transparent keyword and pattern rules with OCR fallback.",
    path: '/apps/smart-document-classifier',
    tags: ["Document Classification","PDF Text Extraction","Image OCR","DOCX Reader","Batch Classification","CSV Export"],
  },
  {
    id: 'smart-document-quality-validation-engine',
    number: '032',
    name: "Smart Document Quality & Validation Engine",
    description: "Inspect document readability, page quality, OCR text, required fields, duplicates and file integrity locally with transparent browser-based checks.",
    path: '/apps/smart-document-quality-validation-engine',
    tags: ["Document Quality","Validation Engine","Blur Detection","OCR Quality","Required Fields","Duplicate Pages"],
  },
]